/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/


EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'Trendline', 235200.00, 20, 'Steel wheels 5J x 14'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'Trendline', 235200.00, 20, 'MIB2-G Entry PQ/MQB radio ROW'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'Trendline', 235200.00, 20, 'Central locking w/ radio remote control, interior controls, without SAFELOCK'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'Trendline', 235200.00, 20, 'Electronic immobilizer, with anti-theft alarm system and interior monitoring'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'Comfortline', 253900.00, 20, 'Alloy wheels 6J x 15'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'Comfortline', 253900.00, 20, 'MIB2-G Entry PQ/MQB radio ROW'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'Comfortline', 253900.00, 20, 'Multi-function steering wheel'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'Comfortline', 253900.00, 20, 'Multi-function steering wheel'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'Comfortline', 253900.00, 20, 'Manual height adjustment for right front seat'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'Comfortline', 253900.00, 20, 'Front fog lamp and cornering lamp'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'Highline ', 281600.00, 20, 'Alloy wheels 7J x 16'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'Highline ', 281600.00, 20, 'MIB2-G Standard Plus PQ/MQB radio ROW/China (GP)'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'Highline ', 281600.00, 20, '6 speakers (passive)'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'Highline ', 281600.00, 20, 'App-Connect'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'Highline ', 281600.00, 20, 'Leather-wrapped multi-function steering wheel'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'Highline ', 281600.00, 20, 'Electronic stability control (ESC)'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'Highline ', 281600.00, 20, 'Cruise control system'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'GT', 317400.00, 20, 'Alloy wheels 7J x 17'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'GT', 317400.00, 20, 'MIB2-G Standard Plus PQ/MQB radio ROW/China (GP)'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'GT', 317400.00, 20, 'Chrome package'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'GT', 317400.00, 20, 'Cruise control system'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'GT', 317400.00, 20, 'Sports comfort seats in front'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'GT', 317400.00, 20, 'Leather-wrapped multi-function steering wheel'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'GT', 317400.00, 20, 'Windshield wiper intermittent control with light/rain sensor'
EXECUTE [dbo].[sp_Insert] 'Polo Vivo Hatch', 'GT', 317400.00, 20, 'Breakaway interior rearview mirror, auto-dimming'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'Polo ', 315000.00, 20, '14" Steel wheels 5J x 14'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'Polo ', 315000.00, 20, 'Multi-function steering wheel'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'Polo ', 315000.00, 20, 'Digital Cockpit'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'Polo ', 315000.00, 20, '6.5" Composition Colour Radio'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'Polo ', 315000.00, 20, 'App-Connect'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'Polo ', 315000.00, 20, 'LED headlamps'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'Polo ', 315000.00, 20, 'Start-stop system with regenerative braking'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'Polo ', 315000.00, 20, 'Automatic headlight control, separate daytime running light'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'Life ', 353600.00, 20, '15" Essex Alloy wheels 5.5J x 15'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'Life ', 353600.00, 20, 'Digital Cockpit'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'Life ', 353600.00, 20, 'LED headlamps'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'Life ', 353600.00, 20, 'Park Distance Control - warning signals for obstacles in the front and rear'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'Life ', 353600.00, 20, 'Cruise control system and speed limiter'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'Life ', 353600.00, 20, 'Mobile phone interface'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'Life ', 353600.00, 20, 'Exterior mirror housings and various add-on parts in body color'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'R-Line ', 426100.00, 20, '16" Valencia Alloy wheels 6.5J x 16'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'R-Line ', 426100.00, 20, 'Composition Media Radio'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'R-Line ', 426100.00, 20, 'Digital Cockpit Pro'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'R-Line ', 426100.00, 20, 'Leather-wrapped multi-function steering wheel with shift paddles'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'R-Line ', 426100.00, 20, 'LED headlamps'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'R-Line ', 426100.00, 20, '2-Zone Climatronic air conditioning'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'R-Line ', 426100.00, 20, 'R-line equipment'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'GTI', 494600.00, 20, '17" Milton Keynes Alloy wheels 7.5J x 17'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'GTI', 494600.00, 20, 'Composition Media Radio'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'GTI', 494600.00, 20, 'Leather-wrapped multi-function touch sports steering wheel, with shifting paddles'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'GTI', 494600.00, 20, '"Art Velour" leather interior trim for seats and door trim'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'GTI', 494600.00, 20, 'IQ. Light LED Matrix Headlamps'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'GTI', 494600.00, 20, 'LED rear combination lamps'
EXECUTE [dbo].[sp_Insert] 'The New Polo', 'GTI', 494600.00, 20, 'Electronic differential lock XDS, dynamic traction support'
EXECUTE [dbo].[sp_Insert] 'The Golf GTI', 'GTI ', 689800.00, 20, '8.25-inch infotainment system, MIB3 Radio'
EXECUTE [dbo].[sp_Insert] 'The Golf GTI', 'GTI ', 689800.00, 20, '18" Richmond Alloy Wheels'
EXECUTE [dbo].[sp_Insert] 'The Golf GTI', 'GTI ', 689800.00, 20, 'Innovision Cockpit'
EXECUTE [dbo].[sp_Insert] 'The Golf GTI', 'GTI ', 689800.00, 20, 'Seat trim covers Vienna leather'
EXECUTE [dbo].[sp_Insert] 'The Golf GTI', 'GTI ', 689800.00, 20, 'Electric seat adjustment with memory feature for driver seat'
EXECUTE [dbo].[sp_Insert] 'The Golf GTI', 'GTI ', 689800.00, 20, 'LED headlights'
EXECUTE [dbo].[sp_Insert] 'The Golf GTI', 'GTI ', 689800.00, 20, 'Ambient lighting, exterior illuminated styling elements at the sides and illuminated grille'
EXECUTE [dbo].[sp_Insert] 'T-Cross ', 'Comfortline ', 368900.00, 20, 'Radio "Composition" invl. Connect package'
EXECUTE [dbo].[sp_Insert] 'T-Cross ', 'Comfortline ', 368900.00, 20, '4 alloy wheels "Belmont" 6J x 16'
EXECUTE [dbo].[sp_Insert] 'T-Cross ', 'Comfortline ', 368900.00, 20, 'Black roof rails'
EXECUTE [dbo].[sp_Insert] 'T-Cross ', 'Comfortline ', 368900.00, 20, 'Park Distance Control - warning signals for obstacles in the front and rear'
EXECUTE [dbo].[sp_Insert] 'T-Cross ', 'Comfortline ', 368900.00, 20, 'Cruise control system and speed limiter'
EXECUTE [dbo].[sp_Insert] 'T-Cross ', 'Comfortline ', 368900.00, 20, 'App-Connect'
EXECUTE [dbo].[sp_Insert] 'T-Cross ', 'Highline ', 448200.00, 20, '4 alloy wheels "Köln" 7J x 18, Black, diamond-turned surface'
EXECUTE [dbo].[sp_Insert] 'T-Cross ', 'Highline ', 448200.00, 20, 'Bright roof rails'
EXECUTE [dbo].[sp_Insert] 'T-Cross ', 'Highline ', 448200.00, 20, 'Leather-wrapped multi-function steering wheel with tiptronic'
EXECUTE [dbo].[sp_Insert] 'T-Cross ', 'Highline ', 448200.00, 20, 'Multi-function display/trip computer "Medium"'
EXECUTE [dbo].[sp_Insert] 'T-Cross ', 'Highline ', 448200.00, 20, 'LED headlamps with lens'
EXECUTE [dbo].[sp_Insert] 'T-Cross ', 'Highline ', 448200.00, 20, '6 speakers (passive)'
EXECUTE [dbo].[sp_Insert] 'T-Cross ', 'R-Line', 486500.00, 20, '4 alloy wheels "Nevada" 7J x 18, Black, diamond-turned surface'
EXECUTE [dbo].[sp_Insert] 'T-Cross ', 'R-Line', 486500.00, 20, 'Bright roof rails'
EXECUTE [dbo].[sp_Insert] 'T-Cross ', 'R-Line', 486500.00, 20, 'Driving profile selection and conventional shock absorber'
EXECUTE [dbo].[sp_Insert] 'T-Cross ', 'R-Line', 486500.00, 20, 'Exterior mirrors, power-adjustable, folding and heated, with front passenger exterior mirror lowering function'
EXECUTE [dbo].[sp_Insert] 'T-Cross ', 'R-Line', 486500.00, 20, 'Multi-function display/trip computer active info display "Entry"'
EXECUTE [dbo].[sp_Insert] 'The New Tiguan Allspace', 'Life ', 671700.00, 20, 'WE CONNECT GO'
EXECUTE [dbo].[sp_Insert] 'The New Tiguan Allspace', 'Life ', 671700.00, 20, 'Multi-color Active Info Display, selection of different info profiles'
EXECUTE [dbo].[sp_Insert] 'The New Tiguan Allspace', 'Life ', 671700.00, 20, 'Climatronic (3-zone) with air conditioning control panel in rear'
EXECUTE [dbo].[sp_Insert] 'The New Tiguan Allspace', 'Life ', 671700.00, 20, 'Electric luggage compartment opening and closing'
EXECUTE [dbo].[sp_Insert] 'The New Tiguan Allspace', 'Life ', 671700.00, 20, 'Park Distance Control - warning signals for obstacles in the front and rear'
EXECUTE [dbo].[sp_Insert] 'The New Tiguan Allspace', 'Life ', 671700.00, 20, 'LED headlamps with cornering light (separate daytime running lamps with special class-A surface)'
EXECUTE [dbo].[sp_Insert] 'The New Tiguan Allspace', 'Life ', 671700.00, 20, 'Alloy wheels 7J x 18'
EXECUTE [dbo].[sp_Insert] 'The New Tiguan Allspace', 'Style ', 726000.00, 20, 'WE CONNECT GO'
EXECUTE [dbo].[sp_Insert] 'The New Tiguan Allspace', 'Style ', 726000.00, 20, 'Multi-color Active Info Display, selection of different info profiles'
EXECUTE [dbo].[sp_Insert] 'The New Tiguan Allspace', 'Style ', 726000.00, 20, 'Power seat adjustment with memory feature for right seat, left seat manually height-adjustable'
EXECUTE [dbo].[sp_Insert] 'The New Tiguan Allspace', 'Style ', 726000.00, 20, 'Seat heater for front seats separately controlled'
EXECUTE [dbo].[sp_Insert] 'The New Tiguan Allspace', 'Style ', 726000.00, 20, 'Park Distance Control - warning signals for obstacles in the front and rear'
EXECUTE [dbo].[sp_Insert] 'The New Tiguan Allspace', 'Style ', 726000.00, 20, 'Electric luggage compartment opening and closing'
EXECUTE [dbo].[sp_Insert] 'The New Tiguan Allspace', 'Style ', 726000.00, 20, 'LED headlamps with cornering light (separate daytime running lamps with special class-A surface)'
EXECUTE [dbo].[sp_Insert] 'The New Tiguan Allspace', 'Style ', 726000.00, 20, 'Alloy wheels 7J x 18'
EXECUTE [dbo].[sp_Insert] 'The New Tiguan Allspace', 'R-Line', 719700.00, 20, 'WE CONNECT GO'
EXECUTE [dbo].[sp_Insert] 'The New Tiguan Allspace', 'R-Line', 719700.00, 20, 'Multi-color Active Info Display, selection of different info profiles'
EXECUTE [dbo].[sp_Insert] 'The New Tiguan Allspace', 'R-Line', 719700.00, 20, 'R-Line leather-wrapped multi-function sports steering wheel'
EXECUTE [dbo].[sp_Insert] 'The New Tiguan Allspace', 'R-Line', 719700.00, 20, 'Ambient lighting, exterior illuminated styling elements in the front'
EXECUTE [dbo].[sp_Insert] 'The New Tiguan Allspace', 'R-Line', 719700.00, 20, 'Power seat adjustment for both front seats with memory feature'
EXECUTE [dbo].[sp_Insert] 'The New Tiguan Allspace', 'R-Line', 719700.00, 20, 'Alloy wheels 8.5J x 19'
EXECUTE [dbo].[sp_Insert] 'Amarok', 'Double Cab Highline', 752100.00, 20, 'Diesel fuel system plus water separator'
EXECUTE [dbo].[sp_Insert] 'Amarok', 'Double Cab Highline', 752100.00, 20, 'Electronic stability control (ESC)'
EXECUTE [dbo].[sp_Insert] 'Amarok', 'Double Cab Highline', 752100.00, 20, 'Differential lock'
EXECUTE [dbo].[sp_Insert] 'Amarok', 'Double Cab Highline', 752100.00, 20, 'Airbag for driver and front passenger with front passenger airbag deactivation'
EXECUTE [dbo].[sp_Insert] 'Amarok', 'Double Cab Highline', 752100.00, 20, 'Side airbag in front with curtain airbag'
EXECUTE [dbo].[sp_Insert] 'Amarok', 'Double Cab Highline', 752100.00, 20, 'Park distance control in front and rear plus rear view camera system'
EXECUTE [dbo].[sp_Insert] 'Amarok', 'Double Cab Highline', 752100.00, 20, 'Gas discharge headlamps (D5/D7 system)'
EXECUTE [dbo].[sp_Insert] 'Amarok', 'Double Cab Highline', 752100.00, 20, 'Cruise control system (CCS)'
EXECUTE [dbo].[sp_Insert] 'Amarok', 'Double Cab “Extreme"', 1058900.00, 20, 'Transmission power take-off'
EXECUTE [dbo].[sp_Insert] 'Amarok', 'Double Cab “Extreme"', 1058900.00, 20, 'Rear bumper (with integrated step)'
EXECUTE [dbo].[sp_Insert] 'Amarok', 'Double Cab “Extreme"', 1058900.00, 20, 'Diesel fuel system plus water separator'
EXECUTE [dbo].[sp_Insert] 'Amarok', 'Double Cab “Extreme"', 1058900.00, 20, 'Leather-wrapped multi-function sports steering wheel with tiptronic'
EXECUTE [dbo].[sp_Insert] 'Amarok', 'Double Cab “Extreme"', 1058900.00, 20, 'Differential lock'
EXECUTE [dbo].[sp_Insert] 'Amarok', 'Double Cab “Extreme"', 1058900.00, 20, 'Park distance control in front and rear plus rear view camera system'
EXECUTE [dbo].[sp_Insert] 'Amarok', 'Double Cab “Extreme"', 1058900.00, 20, 'Voice control'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '5-seater', 574500.00, 20, 'LED headlamps with LED separate daytime running light'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '5-seater', 574500.00, 20, 'Black roof rails'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '5-seater', 574500.00, 20, '4 alloy wheels "Wien" 6.5J x 16'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '5-seater', 574500.00, 20, 'Sliding doors - left and right'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '5-seater', 574500.00, 20, 'Trailer hitch'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '5-seater', 574500.00, 20, 'Radio "Composition" with 8.25-inch colour touch screen with 4 x USB interfaces'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '5-seater', 574500.00, 20, 'Multi-function steering wheel'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '5-seater', 574500.00, 20, 'Bluetooth with App-connect'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '5-seater', 574500.00, 20, 'Park distance control in front and rear'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '5-seater', 574500.00, 20, 'Rear view camera system'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '5-seater', 574500.00, 20, 'Cruise control system and speed limiter'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '5-seater', 574500.00, 20, 'Drawers under front seats'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '7-Seater', 601100.00, 20, 'LED headlamps with LED separate daytime running light'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '7-Seater', 601100.00, 20, 'Black roof rails'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '7-Seater', 601100.00, 20, '4 alloy wheels "Wien" 6.5J x 16'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '7-Seater', 601100.00, 20, 'Sliding doors - left and right'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '7-Seater', 601100.00, 20, 'Trailer hitch'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '7-Seater', 601100.00, 20, 'Radio "Composition" with 8.25-inch colour touch screen with 4 x USB interfaces'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '7-Seater', 601100.00, 20, 'Multi-function steering wheel'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '7-Seater', 601100.00, 20, 'Bluetooth with App-connect'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '7-Seater', 601100.00, 20, 'Park distance control in front and rear'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '7-Seater', 601100.00, 20, 'Rear view camera system'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '7-Seater', 601100.00, 20, 'Cruise control system and speed limiter'
EXECUTE [dbo].[sp_Insert] 'The New Caddy', '7-Seater', 601100.00, 20, 'Drawers under front seats'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Kombi', 'Kombi 5-seater', 503400.00, 20, 'Halogen twin headlamps'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Kombi', 'Kombi 5-seater', 503400.00, 20, 'Roof rails preparation'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Kombi', 'Kombi 5-seater', 503400.00, 20, '4 alloy wheels "Wien" 6.5J x 16'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Kombi', 'Kombi 5-seater', 503400.00, 20, 'Sliding doors - left and right'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Kombi', 'Kombi 5-seater', 503400.00, 20, 'Trailer hitch'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Kombi', 'Kombi 5-seater', 503400.00, 20, 'Radio "Composition Audio" with 6.5-inch color touch screen and one USB interface'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Kombi', 'Kombi 5-seater', 503400.00, 20, 'Multi-function steering wheel'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Kombi', 'Kombi 5-seater', 503400.00, 20, 'Bluetooth'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Kombi', 'Kombi 5-seater', 503400.00, 20, 'Rubber floor covering in passenger/load compartment'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Kombi', 'Kombi 7-seater', 476800.00, 20, 'Halogen twin headlamps'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Kombi', 'Kombi 7-seater', 476800.00, 20, 'Roof rails preparation'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Kombi', 'Kombi 7-seater', 476800.00, 20, '4 alloy wheels "Wien" 6.5J x 16'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Kombi', 'Kombi 7-seater', 476800.00, 20, 'Sliding doors - left and right'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Kombi', 'Kombi 7-seater', 476800.00, 20, 'Trailer hitch'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Kombi', 'Kombi 7-seater', 476800.00, 20, 'Radio "Composition Audio" with 6.5-inch color touch screen and one USB interface'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Kombi', 'Kombi 7-seater', 476800.00, 20, 'Multi-function steering wheel'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Kombi', 'Kombi 7-seater', 476800.00, 20, 'Bluetooth'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Kombi', 'Kombi 7-seater', 476800.00, 20, 'Rear seat bench, split folding in 1st row of seats and 2 single seats in 2nd row of seats'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Kombi', 'Kombi 7-seater', 476800.00, 20, 'Rubber floor covering in passenger/load compartment'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Cargo', 'Cargo ', 460600.00, 20, 'Halogen twin headlamps'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Cargo', 'Cargo ', 460600.00, 20, 'Roof rails preparation'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Cargo', 'Cargo ', 460600.00, 20, 'Sliding doors - left and right'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Cargo', 'Cargo ', 460600.00, 20, 'Rear window equipped with sheet metal'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Cargo', 'Cargo ', 460600.00, 20, 'Radio "Composition Audio" with 6.5-inch color touch screen and one USB interface'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Cargo', 'Cargo ', 460600.00, 20, 'Multi-function steering wheel'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Cargo', 'Cargo ', 460600.00, 20, 'Bluetooth'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Cargo', 'Cargo ', 460600.00, 20, 'Airbag for driver and front passenger with front passenger airbag deactivation'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Cargo', 'Cargo ', 460600.00, 20, 'Central locking w/ radio remote control, interior controls and SAFELOCK'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Cargo', 'Cargo ', 460600.00, 20, 'Anti-theft alarm system, interior monitoring, backup horn, and towing protection'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Cargo', 'Cargo ', 460600.00, 20, 'Seat belt reminder, electric contact in buckle'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Cargo', 'Cargo ', 460600.00, 20, 'Fatigue detection'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Cargo', 'Cargo ', 460600.00, 20, 'Tire pressure monitoring system'
EXECUTE [dbo].[sp_Insert] 'The New Caddy Cargo', 'Cargo ', 460600.00, 20, 'Overhead storage compartment'
EXECUTE [dbo].[sp_Insert] 'The Caravelle 6.1', 'Highline', 1257600.00, 20, 'Diesel fuel system plus water separator with sensor'
EXECUTE [dbo].[sp_Insert] 'The Caravelle 6.1', 'Highline', 1257600.00, 20, 'Electronic stability control (ESC)'
EXECUTE [dbo].[sp_Insert] 'The Caravelle 6.1', 'Highline', 1257600.00, 20, 'Trailer hitch, removable and lockable'
EXECUTE [dbo].[sp_Insert] 'The Caravelle 6.1', 'Highline', 1257600.00, 20, 'Power seats in front, driver seat with memory feature'
EXECUTE [dbo].[sp_Insert] 'The Caravelle 6.1', 'Highline', 1257600.00, 20, 'Sunshade'
EXECUTE [dbo].[sp_Insert] 'The Caravelle 6.1', 'Highline', 1257600.00, 20, 'Seat heater for front seats separately controlled'
EXECUTE [dbo].[sp_Insert] 'The Caravelle 6.1', 'Highline', 1257600.00, 20, '2 swivel seats w/ longitudinal adjustm. on rail system'
EXECUTE [dbo].[sp_Insert] 'The Caravelle 6.1', 'Highline', 1257600.00, 20, 'Cruise control system and speed limiter'
EXECUTE [dbo].[sp_Insert] 'The Caravelle 6.1', 'Highline', 1257600.00, 20, 'Dark tinted glass in rear seat area (Venus 35/Privacy) heat-insulating glass (green) in front'
EXECUTE [dbo].[sp_Insert] 'The Caravelle 6.1', 'Highline', 1257600.00, 20, 'External, USB type C data socket(s) and charging socket(s)'
EXECUTE [dbo].[sp_Insert] 'The California 6.1', 'Coast', 1309100.00, 20, 'Diesel fuel system plus water separator with sensor'
EXECUTE [dbo].[sp_Insert] 'The California 6.1', 'Coast', 1309100.00, 20, 'Trailer hitch, removable and lockable'
EXECUTE [dbo].[sp_Insert] 'The California 6.1', 'Coast', 1309100.00, 20, 'Table for Camper w/ folding chairs'
EXECUTE [dbo].[sp_Insert] 'The California 6.1', 'Coast', 1309100.00, 20, 'Refrigerator with detachable basket'
EXECUTE [dbo].[sp_Insert] 'The California 6.1', 'Coast', 1309100.00, 20, 'Differential lock'
EXECUTE [dbo].[sp_Insert] 'The California 6.1', 'Coast', 1309100.00, 20, 'Pop-up roof'
EXECUTE [dbo].[sp_Insert] 'The California 6.1', 'Coast', 1309100.00, 20, 'Right swivel seat in cab with lumbar support'
EXECUTE [dbo].[sp_Insert] 'The California 6.1', 'Coast', 1309100.00, 20, 'Lane change assist'
EXECUTE [dbo].[sp_Insert] 'The California 6.1', 'Coast', 1309100.00, 20, 'Interior light concept for Camper "Comfort" in passenger compartment'
EXECUTE [dbo].[sp_Insert] 'The California 6.1', 'Coast', 1309100.00, 20, '4 seats'
EXECUTE [dbo].[sp_Insert] 'The California 6.1', 'Coast', 1309100.00, 20, 'With cross wind assist'
EXECUTE [dbo].[sp_Insert] 'The California 6.1', 'Coast', 1309100.00, 20, 'Dark tinted glass in rear seat area (Venus 35/Privacy) heat-insulating glass (green) in front'
EXECUTE [dbo].[sp_Insert] 'Crafter ', 'Panel Van', 658200.00, 20, 'Diesel fuel system plus water separator with sensor'
EXECUTE [dbo].[sp_Insert] 'Crafter ', 'Panel Van', 658200.00, 20, 'Electronic stability control (ESC)'
EXECUTE [dbo].[sp_Insert] 'Crafter ', 'Panel Van', 658200.00, 20, 'Trailer hitch preparation'
EXECUTE [dbo].[sp_Insert] 'Crafter ', 'Panel Van', 658200.00, 20, 'Speed limiter up to 100 km/h'
EXECUTE [dbo].[sp_Insert] 'Crafter ', 'Panel Van', 658200.00, 20, 'Halogen twin headlamps'
EXECUTE [dbo].[sp_Insert] 'Crafter ', 'Panel Van', 658200.00, 20, 'Key for locking system with remote control'
EXECUTE [dbo].[sp_Insert] 'Crafter ', 'Panel Van', 658200.00, 20, 'Smokers package'
EXECUTE [dbo].[sp_Insert] 'Crafter ', 'Panel Van', 658200.00, 20, 'Interface for external use'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Crew Bus', '5 Seater', 691700.00, 20, 'Diesel fuel system plus water separator with sensor'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Crew Bus', '5 Seater', 691700.00, 20, 'Electronic stability control (ESC)'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Crew Bus', '5 Seater', 691700.00, 20, 'Speed-related variable steering assist (Servotronic)'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Crew Bus', '5 Seater', 691700.00, 20, 'Nameplate set Transporter'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Crew Bus', '5 Seater', 691700.00, 20, 'Armrest for right front seat'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Crew Bus', '5 Seater', 691700.00, 20, 'Airbag for driver and front passenger with front passenger airbag deactivation'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Crew Bus', '5 Seater', 691700.00, 20, 'MirrorLink'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Crew Bus', '5 Seater', 691700.00, 20, 'Entry radio (Gen2 GP2) 6.5-inch'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Crew Bus', '8 Seater', 815000.00, 20, 'Diesel fuel system plus water separator with sensor'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Crew Bus', '8 Seater', 815000.00, 20, 'Electronic stability control (ESC)'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Crew Bus', '8 Seater', 815000.00, 20, 'Speed-related variable steering assist (Servotronic)'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Crew Bus', '8 Seater', 815000.00, 20, 'Nameplate set Transporter'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Crew Bus', '8 Seater', 815000.00, 20, 'Armrest for right front seat'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Crew Bus', '8 Seater', 815000.00, 20, 'Airbag for driver and front passenger with front passenger airbag deactivation'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Crew Bus', '8 Seater', 815000.00, 20, 'MirrorLink'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Crew Bus', '8 Seater', 815000.00, 20, 'Entry radio (Gen2 GP2) 6.5-inch'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Crew Bus', '10 Seater', 661400.00, 20, 'Diesel fuel system plus water separator with sensor'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Crew Bus', '10 Seater', 661400.00, 20, 'Speed-related variable steering assist (Servotronic)'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Crew Bus', '10 Seater', 661400.00, 20, 'Nameplate set Transporter'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Crew Bus', '10 Seater', 661400.00, 20, 'Armrest for right front seat'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Crew Bus', '10 Seater', 661400.00, 20, 'Airbag for driver and front passenger with front passenger airbag deactivation'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Crew Bus', '10 Seater', 661400.00, 20, 'MirrorLink'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Crew Bus', '10 Seater', 661400.00, 20, 'Entry radio (Gen2 GP2) 6.5-inch'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Single and Double Cab', 'Single cab', 448000.00, 20, 'Long wheelbase'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Single and Double Cab', 'Single cab', 448000.00, 20, 'Diesel fuel system plus water separator with sensor'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Single and Double Cab', 'Single cab', 448000.00, 20, 'Electronic stability control (ESC) with brake assist system'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Single and Double Cab', 'Single cab', 448000.00, 20, 'Halogen twin headlamps'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Single and Double Cab', 'Single cab', 448000.00, 20, 'Key for locking system with remote control'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Single and Double Cab', 'Single cab', 448000.00, 20, 'Mobile phone interface'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Single and Double Cab', 'Single cab', 448000.00, 20, 'Entry radio (Gen2 GP2) 6.5-inch'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Single and Double Cab', 'Double cab', 527000.00, 20, 'Long wheelbase'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Single and Double Cab', 'Double cab', 527000.00, 20, 'Diesel fuel system plus water separator with sensor'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Single and Double Cab', 'Double cab', 527000.00, 20, 'Halogen twin headlamps'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Single and Double Cab', 'Double cab', 527000.00, 20, 'Entry radio (Gen2 GP2) 6.5-inch'
EXECUTE [dbo].[sp_Insert] 'Transporter 6.1 Single and Double Cab', 'Double cab', 527000.00, 20, 'Electronically controlled air conditioning system'